debug: false

menu:
  shop:
    # Whether shop menu will refresh every 1 second.
    # This will refresh placeholder that displayed in display item lore.
    # But maybe lead to server lag if you have much online players and they are all opening shop GUI.
    update: true
  sell-all:
    size: 54
    title: '&fSell All &7- Esc to confirm sell!'
  # Premium version only
  bedrock:
    title: 'What do you need do?'
    buy-or-sell: 'Buy or Sell?'
    amount: 'Amount'
    amount-tip: 'Type all to sell all!'
  select-more:
    menu: buy-more
    max-amount: 64
  auto-open:
    enabled: true
    menu: main
  click-event:
    buy: 'SHIFT_LEFT'
    sell: 'RIGHT'
    buy-or-sell: 'LEFT'
    # If you want to disable select-amount feature, set this to NEVER.
    select-amount: 'SHIFT_RIGHT'
    sell-all: 'DROP'

use-times:
  default-reset-mode: 'NEVER'
  default-reset-time: '00:00:00'

math:
  enabled: true

send-messages-after-buy: true

display-item:
  auto-set-first-product: true
  add-displayname: ' x{amount}'
  # @+lower case means conditional lore, do not remove them here.
  # Otherwise, the line without this will always display it.
  add-lore:
    - ''
    - '@a&ePurchase: {buy-price}'
    - '@b&eSell: {sell-price}'
    - '@c&#FF7777Player Buy Stock: {buy-times-player}/{buy-limit-player}'
    - '@d&#FF7777Server Buy Stock: {buy-times-server}/{buy-limit-server}'
    - '@e&#FF7777Player Sell Limit: {sell-times-player}/{sell-limit-player}'
    - '@f&#FF7777Server Sell Limit: {sell-times-server}/{sell-limit-server}'
    - '@g '
    - '@g&#ff3300cCan not buy more!'
    - '@g&8Refresh Time: {buy-refresh-player}'
    - '@i '
    - '@i&#ff3300Sold Out!'
    - '@i&8Refresh Time: {buy-refresh-server}'
    - '@h '
    - '@h&#ff3300Can not sell more!'
    - '@h&8Refresh Time: {sell-refresh-player}'
    - '@j'
    - '@j&#ff3300Can not sell more for server!'
    - '@j&8Refresh Time: {sell-refresh-server}'
    - ' '
    - '@a{buy-click}'
    - '@b{sell-click}'
    - '@k&#FFFACDRight-Shift click to pick amount!'
    - '@b&#FFFACDDrop (Q key) to sell all!'

placeholder:
  # Premium version only.
  discount:
    buy:
      mode: MIN
      default: 1
      vip: 0.5
      mvp: 0.3
    sell:
      mode: MAX
      default: 1
      vip: 1.5
      mvp: 2
  discount-conditions:
    vip:
      - 'permission: group.vip'
    mvp:
      - 'permission: group.mvp'
  data:
    can-used-in-amount: true
  refresh:
    format: "yyyy-MM-dd HH:mm:ss"
    never: "Never"
  cooldown:
    format: "yyyy-MM-dd HH:mm:ss"
    now: "Now"
  price:
    split-symbol-any: ', '
    split-symbol-all: ', '
    unknown: "Unknown"
    unknown-price-type: "Unknown Price Type"
    empty: "Price is empty!"
  click:
    enabled: true
    buy: '&#FFFACDLeft-click to buy!'
    sell: '&#FFFACDRight-click to sell!'
    buy-with-no-sell: '&#FFFACDClick to buy!'
    sell-with-no-buy: '&#FFFACDClick to sell!'
    buy-max-limit-player: '&#ff3300You can not buy more!'
    buy-max-limit-server: '&#ff3300SOLD OUT!'
    sell-max-limit-player: '&#ff3300Can not sell more!'
    sell-max-limit-server: '&#ff3300THIS ITEM CAN NOT BE SELLED!'
    buy-price-not-enough: '&#ff3300Do not have enough money to buy!'
    sell-price-not-enough: '&#ff3300Do not have enough item to sell!'
    error: '&#ff3300Error!'
    buy-condition-not-meet: '&#ff3300Not meet the buy condition!'
    sell-condition-not-meet: '&#ff3300Not meet the sell condition!'
    buy-in-cooldown: '&#ff3300In cooldown!'
    sell-in-cooldown: '&#ff3300In cooldown!'

database:
  enabled: false
  jdbc-url: "jdbc:mysql://localhost:3306/ultimateshop?useSSL=false&autoReconnect=true"
  jdbc-class: "com.mysql.cj.jdbc.Driver"
  properties:
    user: root
    password: 123456

prices:
  example:
    economy-plugin: Vault
    amount: 200
    placeholder: '200 Coins'
  mmoitems-example:
    hook-plugin: MMOItems
    hook-item: AXE;;TEST_AXE
    amount: 1
    placeholder: '1 Mythic Axe'

# Premium version only
sell-stick-items:
  A:
    material: STICK
    name: '&dSell stick &7(5 times)'
    lore:
      - '&fClick a chest to use this item!'
      - ''
      - '&cLeft usages: {times}'
    usage-times: 5
  B:
    material: STICK
    name: '&dAdvanced Sell stick &7(50 times)'
    lore:
      - '&fClick a chest to use this item!'
      - ''
      - '&cLeft usages: {times}'
    usage-times: 50

check-class:
  enabled: true
  classes: []